// implementations/react-web-sdk/src/sections/ContentEntry.tsx
import { useOptimization } from '@contentful/optimization-react-web'
import type { JSX, RefObject } from 'react'
import { useEffect, useRef } from 'react'
import { RichTextRenderer } from '../components/RichTextRenderer'
import type { ContentEntry as ContentEntryType, RichTextDocument } from '../types/contentful'

export type EntryClickScenario = 'direct' | 'descendant' | 'ancestor'

interface ContentEntryProps {
  clickScenario?: EntryClickScenario
  entry: ContentEntryType
  observation: 'auto' | 'manual'
}

interface ResolvedOptimizationMeta {
  experienceId: string | undefined
  sticky: boolean | undefined
  variantIndex: number | undefined
}

function isRichTextField(field: unknown): field is RichTextDocument {
  return (
    typeof field === 'object' &&
    field !== null &&
    'nodeType' in field &&
    (field as { nodeType: unknown }).nodeType === 'document' &&
    'content' in field &&
    Array.isArray((field as { content: unknown }).content)
  )
}

function getEntryText(entry: ContentEntryType): string {
  return typeof entry.fields.text === 'string' ? entry.fields.text : 'No content'
}

function resolveOptimizationMeta(selectedOptimization: unknown): ResolvedOptimizationMeta {
  if (typeof selectedOptimization !== 'object' || selectedOptimization === null) {
    return { experienceId: undefined, sticky: undefined, variantIndex: undefined }
  }

  const { experienceId, sticky, variantIndex } = selectedOptimization as {
    experienceId?: unknown
    sticky?: unknown
    variantIndex?: unknown
  }

  return {
    experienceId: typeof experienceId === 'string' ? experienceId : undefined,
    sticky: typeof sticky === 'boolean' ? sticky : undefined,
    variantIndex: typeof variantIndex === 'number' ? variantIndex : undefined,
  }
}

interface ContentDivProps {
  baselineEntry: ContentEntryType
  clickScenario: EntryClickScenario | undefined
  containerRef: RefObject<HTMLDivElement | null>
  meta: ResolvedOptimizationMeta
  observation: 'auto' | 'manual'
  resolvedEntry: ContentEntryType
}

function ContentDiv({
  baselineEntry,
  clickScenario,
  containerRef,
  meta,
  observation,
  resolvedEntry,
}: ContentDivProps): JSX.Element {
  const richTextField = Object.values(resolvedEntry.fields).find(isRichTextField)
  const fullLabel = `Entry: ${resolvedEntry.sys.id}`
  const { experienceId, sticky, variantIndex } = meta

  const autoAttrs =
    observation === 'auto'
      ? {
          'data-ctfl-entry-id': resolvedEntry.sys.id,
          'data-ctfl-baseline-id': baselineEntry.sys.id,
          'data-ctfl-optimization-id': experienceId,
          'data-ctfl-sticky': sticky === undefined ? undefined : String(sticky),
          'data-ctfl-variant-index': variantIndex === undefined ? undefined : String(variantIndex),
          'data-ctfl-hover-duration-update-interval-ms': '1000',
        }
      : { 'data-entry-id': baselineEntry.sys.id }

  const directClickAttrs =
    clickScenario === 'direct' ? ({ 'data-ctfl-clickable': 'true' } as const) : undefined

  return (
    <div
      ref={containerRef}
      data-testid={`content-${baselineEntry.sys.id}`}
      {...autoAttrs}
      {...directClickAttrs}
    >
      <div data-testid={`entry-text-${baselineEntry.sys.id}`} aria-label={fullLabel}>
        {richTextField ? (
          <RichTextRenderer richText={richTextField} />
        ) : (
          <p>{getEntryText(resolvedEntry)}</p>
        )}
        <p>{`[Entry: ${baselineEntry.sys.id}]`}</p>
      </div>

      {clickScenario === 'descendant' ? (
        <button data-testid="entry-click-descendant-button" type="button">
          Trigger entry click tracking from descendant button
        </button>
      ) : null}
    </div>
  )
}

interface TrackedContentProps {
  baselineEntry: ContentEntryType
  clickScenario: EntryClickScenario | undefined
  containerRef: RefObject<HTMLDivElement | null>
  observation: 'auto' | 'manual'
}

function TrackedContent({
  baselineEntry,
  clickScenario,
  containerRef,
  observation,
}: TrackedContentProps): JSX.Element {
  const { interactionTracking, resolveEntry, resolveEntryData } = useOptimization()
  const resolvedEntry = resolveEntry(baselineEntry) as ContentEntryType
  const { selectedOptimization } = resolveEntryData(baselineEntry)
  const meta = resolveOptimizationMeta(selectedOptimization)

  useEffect(() => {
    if (observation !== 'manual') {
      return undefined
    }

    const { current: element } = containerRef
    if (!element) {
      return undefined
    }

    interactionTracking.enableElement('views', element, {
      data: {
        entryId: resolvedEntry.sys.id,
        optimizationId: meta.experienceId,
        sticky: meta.sticky,
        variantIndex: meta.variantIndex,
      },
    })

    return () => {
      interactionTracking.clearElement('views', element)
    }
  }, [
    containerRef,
    interactionTracking,
    meta.experienceId,
    meta.sticky,
    meta.variantIndex,
    observation,
    resolvedEntry.sys.id,
  ])

  const content = (
    <ContentDiv
      baselineEntry={baselineEntry}
      clickScenario={clickScenario}
      containerRef={containerRef}
      meta={meta}
      observation={observation}
      resolvedEntry={resolvedEntry}
    />
  )

  if (clickScenario === 'ancestor' && observation === 'auto') {
    return (
      <div data-ctfl-clickable="true" data-testid="entry-click-ancestor-wrapper">
        {content}
      </div>
    )
  }

  return content
}

export function ContentEntry({
  clickScenario,
  entry,
  observation,
}: ContentEntryProps): JSX.Element {
  const containerRef = useRef<HTMLDivElement | null>(null)

  return (
    <section data-testid={`content-entry-${entry.sys.id}`}>
      <TrackedContent
        baselineEntry={entry}
        clickScenario={clickScenario}
        containerRef={containerRef}
        observation={observation}
      />
    </section>
  )
}

// implementations/angular-web-sdk/src/app/components/content-entry/content-entry.ts
import { NgTemplateOutlet } from '@angular/common'
import {
  afterNextRender,
  Component,
  computed,
  effect,
  ElementRef,
  inject,
  input,
  type OnDestroy,
  signal,
  untracked,
} from '@angular/core'
import { NgContentfulLiveEntry, NgContentfulOptimization } from '@contentful/optimization-angular'
import type { SelectedOptimizationArray } from '@contentful/optimization-web/api-schemas'
import type { ContentfulEntry, RichTextDocument } from '../../types/contentful'
import { RichTextRenderer } from '../rich-text-renderer/rich-text-renderer'

export type EntryClickScenario = 'direct' | 'descendant' | 'ancestor'

function isRichTextField(field: unknown): field is RichTextDocument {
  return (
    typeof field === 'object' &&
    field !== null &&
    'nodeType' in field &&
    (field as { nodeType: unknown }).nodeType === 'document' &&
    'content' in field &&
    Array.isArray((field as { content: unknown }).content)
  )
}

@Component({
  selector: 'app-content-entry',
  imports: [NgTemplateOutlet, RichTextRenderer],
  templateUrl: './content-entry.html',
  providers: [NgContentfulLiveEntry],
})
export class ContentEntry implements OnDestroy {
  readonly entry = input.required<ContentfulEntry>()
  readonly observation = input.required<'auto' | 'manual'>()
  readonly clickScenario = input<EntryClickScenario | undefined>(undefined)
  // Passed down from Home so re-resolution happens whenever selectedOptimizations changes.
  readonly selectedOptimizations = input<SelectedOptimizationArray | undefined>(undefined)
  // undefined = follow global toggle; true = always live; false = always locked
  readonly liveUpdates = input<boolean | undefined>(undefined)

  private readonly optimization = inject(NgContentfulOptimization)
  private readonly elementRef = inject<ElementRef<Element>>(ElementRef)
  private readonly liveEntry = inject(NgContentfulLiveEntry)

  private readonly domReady = signal(false)
  private manualTrackingActive = false

  constructor() {
    effect(() => {
      this.liveEntry.setEntry(this.entry())
      this.liveEntry.setSelectedOptimizations(this.selectedOptimizations())
      this.liveEntry.setLiveUpdatesOverride(this.liveUpdates())
    })

    effect(() => {
      const live = this.liveEntry.isLive()
      if (live) {
        untracked(() => {
          this.liveEntry.clearSnapshot()
        })
      } else {
        untracked(() => {
          this.liveEntry.lockSnapshot()
        })
      }
    })

    afterNextRender(() => {
      this.domReady.set(true)
    })

    effect(() => {
      const ready = this.domReady()
      const mode = this.observation()
      if (!ready || mode !== 'manual' || this.optimization.sdk === undefined) return

      const resolved = this.liveEntry.resolved()
      if (resolved === undefined) return

      if (this.manualTrackingActive) {
        this.optimization.sdk.tracking.clearElement('views', this.elementRef.nativeElement)
        this.manualTrackingActive = false
      }

      this.optimization.sdk.tracking.enableElement('views', this.elementRef.nativeElement, {
        data: {
          entryId: resolved.resolvedId,
          optimizationId: resolved.meta.experienceId,
          sticky: resolved.meta.sticky,
          variantIndex: resolved.meta.variantIndex,
        },
      })
      this.manualTrackingActive = true
    })
  }

  protected readonly resolved = this.liveEntry.resolved

  protected readonly richTextField = computed(() =>
    Object.values(this.liveEntry.resolved()?.resolvedEntry.fields ?? {}).find(isRichTextField),
  )

  protected readonly hasMergeTag = computed(() => {
    const rt = this.richTextField()
    if (!rt) return false
    return JSON.stringify(rt).includes('"nt_mergetag"')
  })

  protected readonly entryText = computed(() => {
    const text: unknown = this.liveEntry.resolved()?.resolvedEntry.fields.text
    return typeof text === 'string' ? text : 'No content'
  })

  ngOnDestroy(): void {
    if (this.manualTrackingActive) {
      this.optimization.sdk?.tracking.clearElement('views', this.elementRef.nativeElement)
      this.manualTrackingActive = false
    }
  }
}
