// implementations/angular-web-sdk/src/app/components/nested-content-item/nested-content-item.ts
import { Component, computed, forwardRef, inject, input } from '@angular/core'
import { toSignal } from '@angular/core/rxjs-interop'
import {
  NgContentfulOptimization,
  NgContentfulOptimizationResolver,
  isRecord,
} from '@contentful/optimization-angular'
import type { ContentfulEntry } from '../../types/contentful'

function isEntry(value: unknown): value is ContentfulEntry {
  return (
    isRecord(value) &&
    isRecord(value.sys) &&
    typeof value.sys.id === 'string' &&
    isRecord(value.fields)
  )
}

@Component({
  selector: 'app-nested-content-item',
  imports: [forwardRef(() => NestedContentItem)],
  templateUrl: './nested-content-item.html',
})
export class NestedContentItem {
  readonly entry = input.required<ContentfulEntry>()

  private readonly optimization = inject(NgContentfulOptimization)
  private readonly resolver = inject(NgContentfulOptimizationResolver)

  private readonly selectedOptimizations = toSignal(this.optimization.selectedOptimizations$)

  protected readonly resolved = computed(() =>
    this.resolver.resolveWithMeta(this.entry(), this.selectedOptimizations()),
  )

  protected readonly entryText = computed(() => {
    const text: unknown = this.resolved().resolvedEntry.fields.text
    return typeof text === 'string' ? text : ''
  })

  protected readonly nestedEntries = computed(() => {
    const nested: unknown = this.resolved().resolvedEntry.fields.nested
    return Array.isArray(nested) ? nested.filter(isEntry) : []
  })
}

// implementations/react-native-sdk/sections/NestedContentItem.tsx
import React from 'react'
import { Text, View } from 'react-native'

import { OptimizedEntry } from '@contentful/optimization-react-native'
import type { Entry } from 'contentful'

interface NestedContentItemProps {
  entry: Entry
}

function isEntry(value: unknown): value is Entry {
  return (
    typeof value === 'object' &&
    value !== null &&
    'sys' in value &&
    typeof value.sys === 'object' &&
    value.sys !== null &&
    'id' in value.sys
  )
}

function renderNestedContentItem(resolvedEntry: Entry): React.JSX.Element {
  const text = typeof resolvedEntry.fields.text === 'string' ? resolvedEntry.fields.text : ''
  const nestedEntries = Array.isArray(resolvedEntry.fields.nested)
    ? (resolvedEntry.fields.nested as unknown[])
    : []
  const fullLabel = `${text} [Entry: ${resolvedEntry.sys.id}]`

  return (
    <View>
      <View testID={`entry-text-${resolvedEntry.sys.id}`} accessibilityLabel={fullLabel}>
        <Text>{text}</Text>
        <Text>{`[Entry: ${resolvedEntry.sys.id}]`}</Text>
      </View>
      {nestedEntries.filter(isEntry).map((nestedEntry) => (
        <OptimizedEntry key={nestedEntry.sys.id} entry={nestedEntry}>
          {renderNestedContentItem}
        </OptimizedEntry>
      ))}
    </View>
  )
}

export function NestedContentItem({ entry }: NestedContentItemProps): React.JSX.Element {
  return (
    <OptimizedEntry entry={entry} testID={`nested-optimization-${entry.sys.id}`}>
      {renderNestedContentItem}
    </OptimizedEntry>
  )
}
