// implementations/web-react/src/sections/ContentEntry.tsx
import { type JSX, useEffect, useMemo, useRef } from 'react'
import { RichTextRenderer } from '../components/RichTextRenderer'
import { useOptimization } from '../optimization/hooks/useOptimization'
import { usePersonalization } from '../optimization/hooks/usePersonalization'
import type { ContentfulEntry, RichTextDocument } from '../types/contentful'
import { isRecord } from '../utils/typeGuards'

interface ContentEntryProps {
  entry: ContentfulEntry
  observation: 'auto' | 'manual'
}

interface PersonalizationMeta {
  experienceId?: string
  sticky?: boolean
  variantIndex?: number
}

interface EntryViewElementOptions {
  readonly dwellTimeMs?: number
  readonly data?: {
    readonly entryId: string
    readonly personalizationId?: string
    readonly sticky?: boolean
    readonly variantIndex?: number
  }
}

interface TrackingApi {
  enableElement: (interaction: 'views', element: Element, options?: EntryViewElementOptions) => void
  clearElement: (interaction: 'views', element: Element) => void
}

interface TrackingApiOwner {
  tracking: TrackingApi
}

function hasTrackingApi(value: unknown): value is TrackingApiOwner {
  if (!isRecord(value)) return false

  const { tracking } = value
  if (!isRecord(tracking)) return false

  return typeof tracking.enableElement === 'function' && typeof tracking.clearElement === 'function'
}

function isRichTextField(field: unknown): field is RichTextDocument {
  return (
    typeof field === 'object' &&
    field !== null &&
    'nodeType' in field &&
    (field as { nodeType: unknown }).nodeType === 'document' &&
    'content' in field &&
    Array.isArray((field as { content: unknown }).content)
  )
}

function getPersonalizationMeta(value: unknown): PersonalizationMeta {
  if (!isRecord(value)) {
    return {}
  }

  const experienceId = typeof value.experienceId === 'string' ? value.experienceId : undefined
  const sticky = typeof value.sticky === 'boolean' ? value.sticky : undefined
  const variantIndex = typeof value.variantIndex === 'number' ? value.variantIndex : undefined

  return { experienceId, sticky, variantIndex }
}

function getEntryText(contentEntry: ContentfulEntry): string {
  return typeof contentEntry.fields.text === 'string' ? contentEntry.fields.text : 'No content'
}

export function ContentEntry({ entry, observation }: ContentEntryProps): JSX.Element {
  const { sdk, isReady } = useOptimization()
  const { resolveEntry } = usePersonalization()
  const containerRef = useRef<HTMLDivElement | null>(null)

  const resolved = useMemo(() => resolveEntry(entry), [entry, resolveEntry])
  const { entry: resolvedEntry, personalization } = resolved

  const { experienceId, sticky, variantIndex } = useMemo(
    () => getPersonalizationMeta(personalization),
    [personalization],
  )

  useEffect(() => {
    if (!isReady || sdk === undefined || observation !== 'manual' || !hasTrackingApi(sdk)) {
      return
    }

    const { current: element } = containerRef
    if (!element) {
      return
    }

    const options: EntryViewElementOptions = {
      data: {
        entryId: resolvedEntry.sys.id,
        personalizationId: experienceId,
        sticky,
        variantIndex,
      },
    }

    sdk.tracking.enableElement('views', element, options)

    return () => {
      sdk.tracking.clearElement('views', element)
    }
  }, [experienceId, isReady, observation, resolvedEntry.sys.id, sdk, sticky, variantIndex])

  const richTextField = Object.values(resolvedEntry.fields).find(isRichTextField)

  const fullLabel = `Entry: ${resolvedEntry.sys.id}`

  const autoTrackingAttributes =
    observation === 'auto'
      ? {
          'data-ctfl-entry-id': resolvedEntry.sys.id,
          'data-ctfl-baseline-id': entry.sys.id,
          'data-ctfl-personalization-id': experienceId,
          'data-ctfl-sticky': sticky === undefined ? undefined : String(sticky),
          'data-ctfl-variant-index': variantIndex === undefined ? undefined : String(variantIndex),
        }
      : undefined

  const manualTrackingAttributes =
    observation === 'manual'
      ? {
          'data-entry-id': entry.sys.id,
        }
      : undefined

  return (
    <section data-testid={`content-entry-${entry.sys.id}`}>
      <div
        ref={containerRef}
        {...autoTrackingAttributes}
        {...manualTrackingAttributes}
        data-testid={`content-${entry.sys.id}`}
      >
        <div data-testid={`entry-text-${entry.sys.id}`} aria-label={fullLabel}>
          {richTextField ? (
            <RichTextRenderer richText={richTextField} />
          ) : (
            <p>{getEntryText(resolvedEntry)}</p>
          )}
          <p>{`[Entry: ${entry.sys.id}]`}</p>
        </div>
      </div>
    </section>
  )
}

// implementations/angular-web-sdk/src/app/components/content-card/content-entry.ts
import { NgTemplateOutlet } from '@angular/common'
import {
  afterNextRender,
  Component,
  computed,
  effect,
  ElementRef,
  inject,
  input,
  type OnDestroy,
  signal,
  untracked,
} from '@angular/core'
import { NgContentfulLiveEntry, NgContentfulOptimization } from '@contentful/optimization-angular'
import type { SelectedOptimizationArray } from '@contentful/optimization-web/api-schemas'
import type { EntryClickScenario } from '../../config/entries'
import type { ContentfulEntry, RichTextDocument } from '../../types/contentful'
import { RichTextRenderer } from '../rich-text-renderer/rich-text-renderer'

function isRichTextField(field: unknown): field is RichTextDocument {
  return (
    typeof field === 'object' &&
    field !== null &&
    'nodeType' in field &&
    (field as { nodeType: unknown }).nodeType === 'document' &&
    'content' in field &&
    Array.isArray((field as { content: unknown }).content)
  )
}

@Component({
  selector: 'app-content-entry',
  imports: [NgTemplateOutlet, RichTextRenderer],
  templateUrl: './content-entry.html',
  providers: [NgContentfulLiveEntry],
})
export class ContentEntry implements OnDestroy {
  // inputs
  readonly entry = input.required<ContentfulEntry>()
  readonly observation = input.required<'auto' | 'manual'>()
  readonly clickScenario = input<EntryClickScenario | undefined>(undefined)
  readonly selectedOptimizations = input<SelectedOptimizationArray | undefined>(undefined)
  readonly liveUpdates = input<boolean | undefined>(undefined)

  // injected dependencies
  private readonly optimization = inject(NgContentfulOptimization)
  private readonly elementRef = inject<ElementRef<Element>>(ElementRef)
  private readonly liveEntry = inject(NgContentfulLiveEntry)

  // private state
  private readonly domReady = signal(false)
  private manualTrackingActive = false

  // constructor (effects)
  constructor() {
    effect(() => {
      this.liveEntry.setEntry(this.entry())
      this.liveEntry.setSelectedOptimizations(this.selectedOptimizations())
      this.liveEntry.setLiveUpdatesOverride(this.liveUpdates())
    })

    effect(() => {
      const live = this.liveEntry.isLive()
      if (live) {
        untracked(() => {
          this.liveEntry.clearSnapshot()
        })
      } else {
        untracked(() => {
          this.liveEntry.lockSnapshot()
        })
      }
    })

    afterNextRender(() => {
      this.domReady.set(true)
    })

    effect(() => {
      const ready = this.domReady()
      const mode = this.observation()
      if (!ready || mode !== 'manual' || this.optimization.sdk === undefined) return

      const resolved = this.liveEntry.resolved()
      if (resolved === undefined) return

      if (this.manualTrackingActive) {
        this.optimization.sdk.tracking.clearElement('views', this.elementRef.nativeElement)
        this.manualTrackingActive = false
      }

      this.optimization.sdk.tracking.enableElement('views', this.elementRef.nativeElement, {
        data: {
          entryId: resolved.resolvedId,
          optimizationId: resolved.meta.experienceId,
          sticky: resolved.meta.sticky,
          variantIndex: resolved.meta.variantIndex,
        },
      })
      this.manualTrackingActive = true
    })
  }

  // protected state (template-facing)
  protected readonly resolved = this.liveEntry.resolved
  protected readonly richTextField = computed(() =>
    Object.values(this.liveEntry.resolved()?.resolvedEntry.fields ?? {}).find(isRichTextField),
  )
  protected readonly hasMergeTag = computed(() => {
    const rt = this.richTextField()
    if (!rt) return false
    return JSON.stringify(rt).includes('"nt_mergetag"')
  })
  protected readonly entryText = computed(() => {
    const text: unknown = this.liveEntry.resolved()?.resolvedEntry.fields.text
    return typeof text === 'string' ? text : 'No content'
  })

  // lifecycle
  ngOnDestroy(): void {
    if (this.manualTrackingActive) {
      this.optimization.sdk?.tracking.clearElement('views', this.elementRef.nativeElement)
      this.manualTrackingActive = false
    }
  }
}
