// implementations/angular-web-sdk/src/app/components/rich-text-renderer/rich-text-renderer.ts
import { Component, computed, inject, input } from '@angular/core'
import { DomSanitizer, type SafeHtml } from '@angular/platform-browser'
import {
  isMergeTagEntry,
  isRecord,
  NgContentfulOptimizationResolver,
} from '@contentful/optimization-angular'
import { BLOCKS, INLINES } from '@contentful/rich-text-types'
import type { RichTextDocument } from '../../types/contentful'

function escape(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

type GetMergeTag = (target: unknown) => string
type NodeRenderer = (
  children: () => string,
  data: Record<string, unknown>,
  getMergeTag: GetMergeTag,
) => string

const RENDERERS: Partial<Record<string, NodeRenderer>> = {
  [BLOCKS.PARAGRAPH]: (children) => `<p>${children()}</p>`,
  [BLOCKS.HEADING_1]: (children) => `<h1>${children()}</h1>`,
  [BLOCKS.HEADING_2]: (children) => `<h2>${children()}</h2>`,
  [BLOCKS.HEADING_3]: (children) => `<h3>${children()}</h3>`,
  [BLOCKS.HEADING_4]: (children) => `<h4>${children()}</h4>`,
  [BLOCKS.HEADING_5]: (children) => `<h5>${children()}</h5>`,
  [BLOCKS.HEADING_6]: (children) => `<h6>${children()}</h6>`,
  [BLOCKS.UL_LIST]: (children) => `<ul>${children()}</ul>`,
  [BLOCKS.OL_LIST]: (children) => `<ol>${children()}</ol>`,
  [BLOCKS.LIST_ITEM]: (children) => `<li>${children()}</li>`,
  [BLOCKS.QUOTE]: (children) => `<blockquote>${children()}</blockquote>`,
  [BLOCKS.HR]: () => `<hr />`,
  [BLOCKS.EMBEDDED_ENTRY]: () => '',
  [BLOCKS.EMBEDDED_ASSET]: () => '',
  [INLINES.HYPERLINK]: (children, data) => {
    const uri = typeof data.uri === 'string' ? escape(data.uri) : '#'
    return `<a href="${uri}">${children()}</a>`
  },
  [INLINES.EMBEDDED_ENTRY]: (_children, data, getMergeTag) => escape(getMergeTag(data.target)),
}

function renderNode(node: unknown, getMergeTag: GetMergeTag): string {
  if (!isRecord(node)) return ''
  const nodeType = typeof node.nodeType === 'string' ? node.nodeType : ''
  const value = typeof node.value === 'string' ? node.value : ''
  const content = Array.isArray(node.content) ? node.content : []
  const data = isRecord(node.data) ? node.data : {}
  const children = (): string => content.map((c) => renderNode(c, getMergeTag)).join('')

  if (nodeType === 'text') return escape(value)
  const { [nodeType]: renderer } = RENDERERS
  return renderer !== undefined ? renderer(children, data, getMergeTag) : children()
}

@Component({
  selector: 'app-rich-text-renderer',
  template: `<div class="rich-text" [innerHTML]="html()"></div>`,
})
export class RichTextRenderer {
  readonly richText = input.required<RichTextDocument>()

  private readonly resolver = inject(NgContentfulOptimizationResolver)
  private readonly sanitizer = inject(DomSanitizer)

  protected readonly html = computed<SafeHtml>(() => {
    const getMergeTag = (target: unknown): string => {
      if (!isMergeTagEntry(target)) return '[Merge Tag]'
      return this.resolver.getMergeTagValue(target)
    }
    const raw = this.richText()
      .content.map((node) => renderNode(node, getMergeTag))
      .join('')
    return this.sanitizer.bypassSecurityTrustHtml(raw)
  })
}

// implementations/react-web-sdk/src/components/RichTextRenderer.tsx
import type { OptimizedEntryRenderContext } from '@contentful/optimization-react-web'
import {
  isMergeTagEntry,
  isRecord,
  isUnresolvedEntryLink,
} from '@contentful/optimization-react-web/api-schemas'
import { documentToReactComponents, type Options } from '@contentful/rich-text-react-renderer'
import { INLINES } from '@contentful/rich-text-types'
import type { JSX } from 'react'
import type { RichTextDocument } from '../types/contentful'

interface RichTextNode {
  nodeType: string
  content?: RichTextNode[]
  data?: Record<string, unknown>
  value?: string
}

interface RichTextRendererProps {
  getMergeTagValue: GetMergeTagValue
  richText: RichTextDocument
}

type GetMergeTagValue = OptimizedEntryRenderContext['getMergeTagValue']

const EMBEDDED_ENTRY_NODE_TYPE = 'embedded-entry-inline'

function getMergeTagText(target: unknown, getMergeTagValue: GetMergeTagValue): string {
  if (isUnresolvedEntryLink(target) || !isMergeTagEntry(target)) {
    return '[Merge Tag]'
  }

  return getMergeTagValue(target) ?? ''
}

function extractTextContent(node: RichTextNode, getMergeTagValue: GetMergeTagValue): string {
  if (node.nodeType === 'text' && typeof node.value === 'string') {
    return node.value
  }

  if (node.nodeType === EMBEDDED_ENTRY_NODE_TYPE && isRecord(node.data) && 'target' in node.data) {
    return getMergeTagText(node.data.target, getMergeTagValue)
  }

  if (Array.isArray(node.content)) {
    return node.content.map((child) => extractTextContent(child, getMergeTagValue)).join(' ')
  }

  return ''
}

export function getRichTextContent(
  richText: RichTextDocument,
  getMergeTagValue: GetMergeTagValue,
): string {
  return richText.content
    .map((node) => extractTextContent(node, getMergeTagValue))
    .join(' ')
    .trim()
}

export function RichTextRenderer({
  getMergeTagValue,
  richText,
}: RichTextRendererProps): JSX.Element {
  const renderOptions: Options = {
    renderNode: {
      [INLINES.EMBEDDED_ENTRY]: (node): string => {
        const { data } = node
        if (!isRecord(data) || !('target' in data)) {
          return '[Merge Tag]'
        }

        return getMergeTagText(data.target, getMergeTagValue)
      },
    },
  }

  return <>{documentToReactComponents(richText, renderOptions)}</>
}
