// implementations/react-web-sdk/src/sections/NestedContentEntry.tsx
import { type JSX } from 'react'
import type { ContentfulEntry } from '../types/contentful'
import { NestedContentItem } from './NestedContentItem'

interface NestedContentEntryProps {
  entry: ContentfulEntry
}

export function NestedContentEntry({ entry }: NestedContentEntryProps): JSX.Element {
  return (
    <section data-testid={`nested-content-entry-${entry.sys.id}`}>
      <NestedContentItem entry={entry} />
    </section>
  )
}

// implementations/angular-web-sdk/src/app/components/nested-content-entry/nested-content-entry.ts
import { Component, input } from '@angular/core'
import type { ContentfulEntry } from '../../types/contentful'
import { NestedContentItem } from '../nested-content-item/nested-content-item'

@Component({
  selector: 'app-nested-content-entry',
  imports: [NestedContentItem],
  template: `
    <section [attr.data-testid]="'nested-content-entry-' + entry().sys.id">
      <app-nested-content-item [entry]="entry()" />
    </section>
  `,
})
export class NestedContentEntry {
  readonly entry = input.required<ContentfulEntry>()
}
