// implementations/angular-web-sdk/src/app/components/nested-content-item/nested-content-item.ts
import { Component, computed, forwardRef, inject, input } from '@angular/core'
import { toSignal } from '@angular/core/rxjs-interop'
import {
  NgContentfulOptimization,
  NgContentfulOptimizationResolver,
  isRecord,
} from '@contentful/optimization-angular'
import type { ContentfulEntry } from '../../types/contentful'

function isEntry(value: unknown): value is ContentfulEntry {
  return (
    isRecord(value) &&
    isRecord(value.sys) &&
    typeof value.sys.id === 'string' &&
    isRecord(value.fields)
  )
}

@Component({
  selector: 'app-nested-content-item',
  imports: [forwardRef(() => NestedContentItem)],
  templateUrl: './nested-content-item.html',
})
export class NestedContentItem {
  readonly entry = input.required<ContentfulEntry>()

  private readonly optimization = inject(NgContentfulOptimization)
  private readonly resolver = inject(NgContentfulOptimizationResolver)

  private readonly selectedOptimizations = toSignal(this.optimization.selectedOptimizations$)

  protected readonly resolved = computed(() =>
    this.resolver.resolveWithMeta(this.entry(), this.selectedOptimizations()),
  )

  protected readonly entryText = computed(() => {
    const text: unknown = this.resolved().resolvedEntry.fields.text
    return typeof text === 'string' ? text : ''
  })

  protected readonly nestedEntries = computed(() => {
    const nested: unknown = this.resolved().resolvedEntry.fields.nested
    return Array.isArray(nested) ? nested.filter(isEntry) : []
  })
}

// implementations/react-web-sdk/src/sections/NestedContentItem.tsx
import { OptimizedEntry } from '@contentful/optimization-react-web'
import type { JSX } from 'react'
import type { ContentEntry } from '../types/contentful'
import { isRecord } from '../utils/typeGuards'

interface NestedContentItemProps {
  entry: ContentEntry
}

function isEntry(value: unknown): value is ContentEntry {
  return (
    isRecord(value) &&
    isRecord(value.sys) &&
    typeof value.sys.id === 'string' &&
    isRecord(value.fields)
  )
}

function renderText(entry: ContentEntry): string {
  return typeof entry.fields.text === 'string' ? entry.fields.text : ''
}

export function NestedContentItem({ entry }: NestedContentItemProps): JSX.Element {
  return (
    <OptimizedEntry baselineEntry={entry} hoverDurationUpdateIntervalMs={1000}>
      {(resolvedEntry) => {
        const asCf = resolvedEntry as ContentEntry
        const nestedEntries = Array.isArray(asCf.fields.nested) ? asCf.fields.nested : []
        const text = renderText(asCf)
        const fullLabel = `${text} [Entry: ${resolvedEntry.sys.id}]`

        return (
          <div>
            <div data-testid={`entry-text-${resolvedEntry.sys.id}`} aria-label={fullLabel}>
              <p>{text}</p>
              <p>{`[Entry: ${resolvedEntry.sys.id}]`}</p>
            </div>

            {nestedEntries.filter(isEntry).map((nestedEntry) => (
              <NestedContentItem key={nestedEntry.sys.id} entry={nestedEntry} />
            ))}
          </div>
        )
      }}
    </OptimizedEntry>
  )
}
