// implementations/angular-web-sdk/src/app/sections/content-entry/content-entry.ts
import { NgTemplateOutlet } from '@angular/common'
import {
  afterNextRender,
  Component,
  computed,
  effect,
  ElementRef,
  inject,
  input,
  type OnDestroy,
  signal,
  untracked,
} from '@angular/core'
import { NgContentfulLiveEntry, NgContentfulOptimization } from '@contentful/optimization-angular'
import type { SelectedOptimizationArray } from '@contentful/optimization-web/api-schemas'
import { RichTextRenderer } from '../../components/rich-text-renderer/rich-text-renderer'
import type { ContentfulEntry, RichTextDocument } from '../../types/contentful'

export type EntryClickScenario = 'direct' | 'descendant' | 'ancestor'

function isRichTextField(field: unknown): field is RichTextDocument {
  return (
    typeof field === 'object' &&
    field !== null &&
    'nodeType' in field &&
    (field as { nodeType: unknown }).nodeType === 'document' &&
    'content' in field &&
    Array.isArray((field as { content: unknown }).content)
  )
}

@Component({
  selector: 'app-content-entry',
  imports: [NgTemplateOutlet, RichTextRenderer],
  templateUrl: './content-entry.html',
  providers: [NgContentfulLiveEntry],
})
export class ContentEntry implements OnDestroy {
  readonly entry = input.required<ContentfulEntry>()
  readonly observation = input.required<'auto' | 'manual'>()
  readonly clickScenario = input<EntryClickScenario | undefined>(undefined)
  // Passed down from Home so re-resolution happens whenever selectedOptimizations changes.
  readonly selectedOptimizations = input<SelectedOptimizationArray | undefined>(undefined)
  // undefined = follow global toggle; true = always live; false = always locked
  readonly liveUpdates = input<boolean | undefined>(undefined)

  private readonly optimization = inject(NgContentfulOptimization)
  private readonly elementRef = inject<ElementRef<Element>>(ElementRef)
  private readonly liveEntry = inject(NgContentfulLiveEntry)

  private readonly domReady = signal(false)
  private manualTrackingActive = false

  constructor() {
    effect(() => {
      this.liveEntry.setEntry(this.entry())
      this.liveEntry.setSelectedOptimizations(this.selectedOptimizations())
      this.liveEntry.setLiveUpdatesOverride(this.liveUpdates())
    })

    effect(() => {
      const live = this.liveEntry.isLive()
      if (live) {
        untracked(() => {
          this.liveEntry.clearSnapshot()
        })
      } else {
        untracked(() => {
          this.liveEntry.lockSnapshot()
        })
      }
    })

    afterNextRender(() => {
      this.domReady.set(true)
    })

    effect(() => {
      const ready = this.domReady()
      const mode = this.observation()
      if (!ready || mode !== 'manual' || this.optimization.sdk === undefined) return

      const resolved = this.liveEntry.resolved()
      if (resolved === undefined) return

      if (this.manualTrackingActive) {
        this.optimization.sdk.tracking.clearElement('views', this.elementRef.nativeElement)
        this.manualTrackingActive = false
      }

      this.optimization.sdk.tracking.enableElement('views', this.elementRef.nativeElement, {
        data: {
          entryId: resolved.resolvedId,
          optimizationId: resolved.meta.experienceId,
          sticky: resolved.meta.sticky,
          variantIndex: resolved.meta.variantIndex,
        },
      })
      this.manualTrackingActive = true
    })
  }

  protected readonly resolved = this.liveEntry.resolved

  protected readonly richTextField = computed(() =>
    Object.values(this.liveEntry.resolved()?.resolvedEntry.fields ?? {}).find(isRichTextField),
  )

  protected readonly hasMergeTag = computed(() => {
    const rt = this.richTextField()
    if (!rt) return false
    return JSON.stringify(rt).includes('"nt_mergetag"')
  })

  protected readonly entryText = computed(() => {
    const text: unknown = this.liveEntry.resolved()?.resolvedEntry.fields.text
    return typeof text === 'string' ? text : 'No content'
  })

  ngOnDestroy(): void {
    if (this.manualTrackingActive) {
      this.optimization.sdk?.tracking.clearElement('views', this.elementRef.nativeElement)
      this.manualTrackingActive = false
    }
  }
}

// implementations/nextjs-sdk_hybrid/sections/ContentEntry.tsx
import { OptimizedEntry, useOptimization } from '@contentful/optimization-nextjs/client'
import type { JSX } from 'react'
import { useEffect, useRef } from 'react'
import { RichTextRenderer } from '../components/RichTextRenderer'
import type { ContentEntry as ContentEntryType, RichTextDocument } from '../types/contentful'

export type EntryClickScenario = 'direct' | 'descendant' | 'ancestor'
type ViewTrackingMode = 'auto' | 'manual'

interface ContentEntryProps {
  clickScenario?: EntryClickScenario
  entry: ContentEntryType
  viewTracking: ViewTrackingMode
}

const HOVER_DURATION_UPDATE_INTERVAL_MS = 1000

function isRichTextField(field: unknown): field is RichTextDocument {
  return (
    typeof field === 'object' &&
    field !== null &&
    'nodeType' in field &&
    (field as { nodeType: unknown }).nodeType === 'document' &&
    'content' in field &&
    Array.isArray((field as { content: unknown }).content)
  )
}

function getEntryText(entry: ContentEntryType): string {
  return typeof entry.fields.text === 'string' ? entry.fields.text : 'No content'
}

export function ContentEntry({
  clickScenario,
  entry,
  viewTracking,
}: ContentEntryProps): JSX.Element {
  const sdk = useOptimization()
  const manuallyTrackedElement = useRef<HTMLDivElement | null>(null)
  const autoTrackViews = viewTracking === 'auto'

  useEffect(
    () => () => {
      const { current } = manuallyTrackedElement
      if (!current) {
        return
      }

      sdk.tracking.clearElement('views', current)
    },
    [sdk.tracking],
  )

  const updateManualViewElement = (element: HTMLDivElement | null, entryId: string): void => {
    const { current: previousElement } = manuallyTrackedElement

    if (previousElement && previousElement !== element) {
      sdk.tracking.clearElement('views', previousElement)
    }

    manuallyTrackedElement.current = element

    if (!element || viewTracking !== 'manual') {
      return
    }

    sdk.tracking.enableElement('views', element, {
      data: { entryId },
    })
  }

  return (
    <section data-testid={`content-entry-${entry.sys.id}`}>
      <OptimizedEntry
        baselineEntry={entry}
        clickable={autoTrackViews && clickScenario === 'direct'}
        hoverDurationUpdateIntervalMs={
          autoTrackViews ? HOVER_DURATION_UPDATE_INTERVAL_MS : undefined
        }
        trackViews={autoTrackViews ? undefined : false}
      >
        {(resolvedEntry) => {
          const asCf = resolvedEntry as ContentEntryType
          const richTextField = Object.values(asCf.fields).find(isRichTextField)
          const fullLabel = `Entry: ${asCf.sys.id}`

          const content = (
            <div
              ref={
                viewTracking === 'manual'
                  ? (element) => {
                      updateManualViewElement(element, asCf.sys.id)
                    }
                  : undefined
              }
              data-testid={`content-${entry.sys.id}`}
            >
              <div data-testid={`entry-text-${entry.sys.id}`} aria-label={fullLabel}>
                {richTextField ? (
                  <RichTextRenderer richText={richTextField} />
                ) : (
                  <p>{getEntryText(asCf)}</p>
                )}
                <p>{`[Entry: ${entry.sys.id}]`}</p>
              </div>

              {clickScenario === 'descendant' ? (
                <button data-testid="entry-click-descendant-button" type="button">
                  Trigger entry click tracking from descendant button
                </button>
              ) : null}
            </div>
          )

          if (autoTrackViews && clickScenario === 'ancestor') {
            return (
              <div data-ctfl-clickable="true" data-testid="entry-click-ancestor-wrapper">
                {content}
              </div>
            )
          }

          return content
        }}
      </OptimizedEntry>
    </section>
  )
}
