// implementations/angular-web-sdk/src/app/sections/nested-content-item/nested-content-item.ts
import { Component, computed, forwardRef, inject, input } from '@angular/core'
import { toSignal } from '@angular/core/rxjs-interop'
import { Optimization } from '../../optimization/optimization'
import { OptimizationResolver } from '../../optimization/optimization-resolver'
import type { ContentfulEntry } from '../../types/contentful'
import { getSelectedOptimizationMeta, isEntry } from '../../utils/type-guards'

@Component({
  selector: 'app-nested-content-item',
  imports: [forwardRef(() => NestedContentItem)],
  templateUrl: './nested-content-item.html',
})
export class NestedContentItem {
  readonly entry = input.required<ContentfulEntry>()

  private readonly optimization = inject(Optimization)
  private readonly resolver = inject(OptimizationResolver)

  protected readonly selectedOptimizations = toSignal(this.optimization.selectedOptimizations$)

  protected readonly resolved = computed(() =>
    this.resolver.resolveEntry(this.entry(), this.selectedOptimizations()),
  )

  protected readonly resolvedEntry = computed(() => this.resolved().entry as ContentfulEntry)

  protected readonly meta = computed(() =>
    getSelectedOptimizationMeta(this.resolved().selectedOptimization),
  )

  protected readonly baselineId = computed(() => this.entry().sys.id)
  protected readonly resolvedId = computed(() => this.resolvedEntry().sys.id)
  protected readonly isVariant = computed(() => this.meta().experienceId !== undefined)

  protected readonly entryText = computed(() => {
    const text: unknown = this.resolvedEntry().fields.text
    return typeof text === 'string' ? text : ''
  })

  protected readonly stickyAttr = computed(() => {
    const { sticky } = this.meta()
    return sticky === undefined ? null : String(sticky)
  })

  protected readonly variantIndexAttr = computed(() => {
    const { variantIndex } = this.meta()
    return variantIndex === undefined ? null : String(variantIndex)
  })

  protected readonly nestedEntries = computed(() => {
    const nested: unknown = this.resolvedEntry().fields.nested
    return Array.isArray(nested) ? nested.filter(isEntry) : []
  })
}

// implementations/web-sdk_react/src/sections/NestedContentItem.tsx
import { useMemo, type JSX } from 'react'
import { useOptimizationResolver } from '../optimization/hooks/useOptimizationResolver'
import type { ContentfulEntry } from '../types/contentful'
import { isRecord } from '../utils/typeGuards'

interface NestedContentItemProps {
  entry: ContentfulEntry
}

interface SelectedOptimizationMeta {
  experienceId?: string
  sticky?: boolean
  variantIndex?: number
}

function isEntry(value: unknown): value is ContentfulEntry {
  return (
    isRecord(value) &&
    isRecord(value.sys) &&
    typeof value.sys.id === 'string' &&
    isRecord(value.fields)
  )
}

function getSelectedOptimizationMeta(value: unknown): SelectedOptimizationMeta {
  if (!isRecord(value)) {
    return {}
  }

  return {
    experienceId: typeof value.experienceId === 'string' ? value.experienceId : undefined,
    sticky: typeof value.sticky === 'boolean' ? value.sticky : undefined,
    variantIndex: typeof value.variantIndex === 'number' ? value.variantIndex : undefined,
  }
}

function renderText(contentEntry: ContentfulEntry): string {
  return typeof contentEntry.fields.text === 'string' ? contentEntry.fields.text : ''
}

export function NestedContentItem({ entry }: NestedContentItemProps): JSX.Element {
  const { resolveEntry } = useOptimizationResolver()
  const resolved = useMemo(() => resolveEntry(entry), [entry, resolveEntry])
  const { entry: resolvedEntry, selectedOptimization } = resolved

  const { experienceId, sticky, variantIndex } = useMemo(
    () => getSelectedOptimizationMeta(selectedOptimization),
    [selectedOptimization],
  )

  const nestedEntries = Array.isArray(resolvedEntry.fields.nested)
    ? resolvedEntry.fields.nested
    : []

  const text = renderText(resolvedEntry)
  const fullLabel = `${text} [Entry: ${resolvedEntry.sys.id}]`

  return (
    <div
      data-ctfl-entry-id={resolvedEntry.sys.id}
      data-ctfl-baseline-id={entry.sys.id}
      data-ctfl-optimization-id={experienceId}
      data-ctfl-sticky={sticky === undefined ? undefined : String(sticky)}
      data-ctfl-variant-index={variantIndex === undefined ? undefined : String(variantIndex)}
    >
      <div data-testid={`entry-text-${resolvedEntry.sys.id}`} aria-label={fullLabel}>
        <p>{text}</p>
        <p>{`[Entry: ${resolvedEntry.sys.id}]`}</p>
      </div>

      {nestedEntries.filter(isEntry).map((nestedEntry) => (
        <NestedContentItem key={nestedEntry.sys.id} entry={nestedEntry} />
      ))}
    </div>
  )
}
